export const paths = {
  LANDING_PAGE: "/",
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  REGISTER_GOOGLE_PAGE: "/register_Google",
  VILLAGE_PAGE: "/village",
  VILLAGE_PROFILE_PAGE: "/village/profile",
  DETAIL_VILLAGE_PAGE: "/village/detail/:id",
  INNOVATOR_PAGE: "/innovator",
  INNOVATOR_PROFILE_PAGE: "/innovator/profile",
  DETAIL_INNOVATOR_PAGE: "/innovator/detail/:id",
  INNOVATION_PAGE: "/innovation",
  ADD_INNOVATION: "/innovation/add",
  INNOVATION_CATEGORY_PAGE: "/innovation/:category",
  DETAIL_INNOVATION_PAGE: "/innovation/detail/:id",
};
